# Generated by Django 4.2.11 on 2024-04-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nombres",
        ),
    ]
