volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db_eventos:
    image: postgres:15-alpine
    container_name: db_eventos
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      eventos:
        ipv4_address: 30.10.10.43

  smtp-server:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      eventos:
        ipv4_address: 30.10.10.42

  redis:
    image: redis:7.0.12
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data:rw
    networks:
      eventos:
        ipv4_address: 30.10.10.41

networks:
  eventos:
    ipam:
      config:
        - subnet: 30.10.10.0/24
          gateway: 30.10.10.1
