volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db_eventos:
    image: postgres:15-alpine
    container_name: db_eventos
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    networks:
      eventos:
        ipv4_address: 30.10.10.43

  smtp-server:
    image: mailhog/mailhog
    ports:
      - '1025'
      - '8025'
    networks:
      eventos:
        ipv4_address: 30.10.10.42

networks:
  eventos:
    ipam:
      config:
        - subnet: 20.10.10.0/24
          gateway: 20.10.10.1
