# Generated by Django 4.2.11 on 2024-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apellidos",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="datos_actualizados",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nombres",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
