# Generated by Django 4.2.11 on 2024-04-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='eventos',
        ),
        migrations.AlterModelTable(
            name='tipoevento',
            table='tipo_evento',
        ),
    ]
