# Generated by Django 4.2.11 on 2024-04-28 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletos",
            name="estado_vendedor",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="boletos",
            name="usuario",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="boletos",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Vendedor",
        ),
    ]
