# Generated by Django 4.2.11 on 2024-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="arte",
            field=models.ImageField(upload_to="artes/%Y-%m-%d"),
        ),
    ]
