# Generated by Django 4.2.11 on 2024-04-15 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_vendedor_boletos"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
