# Generated by Django 4.2.11 on 2024-04-26 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import app.apps.utils.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("organizador", models.CharField(max_length=500)),
                ("descripcion", models.TextField()),
                ("direccion", models.CharField(max_length=1000)),
                ("cantidad_boletos", models.SmallIntegerField(default=0)),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        help_text="Fecha y hora del evento",
                        verbose_name="fecha y hora del evento",
                    ),
                ),
                ("valor", models.FloatField()),
                ("arte", models.ImageField(upload_to="artes/%Y-%m-%d")),
                ("estado", models.BooleanField(default=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha registro",
                        verbose_name="fecha registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "eventos",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("estado", models.BooleanField(default=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha registro",
                        verbose_name="fecha registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
                "db_table": "tipo_evento",
                "ordering": ["fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha registro",
                        verbose_name="fecha registro",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
                "db_table": "vendedor",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="tipo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventos.tipoevento"),
        ),
        migrations.AddField(
            model_name="evento",
            name="usuario",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Boletos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(default=0)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha registro",
                        verbose_name="fecha registro",
                    ),
                ),
                (
                    "estado",
                    models.CharField(default=app.apps.utils.enums.EstadoBoleto["ASIGNADO"], max_length=20),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha venta",
                        null=True,
                        verbose_name="fecha venta",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventos.evento"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto",
                "verbose_name_plural": "Boletos",
                "db_table": "boletos",
                "ordering": ["id"],
            },
        ),
    ]
